[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "user"
path = "user/user.rs"

[dependencies]
tonic = "0.8.3"
