[package]
name = "redis"
version = "0.1.0"
edition = "2024"

[dependencies]
deadpool-redis = { version = "0.21.1", features = ["sentinel"]}
dotenvy = "0.15.7"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "sync"] }
