[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
transport = { path = "../transport" }
futures = "0.1.18"
multiaddr = "0.17.0"
tokio-core = "0.1"
tokio-io = "0.1"
