[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
rand = "0.8.5"
ed25519 = "2.1.0"
ring-compat = "0.6.0"
rand_core = "0.6.4"
